# Generated by Django 6.0.7 on 2026-07-17 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('commonlocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commonlocation')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(upload_to='centers/logos/')),
                ('website', models.URLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('common.commonlocation', models.Model),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('commonlocation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.commonlocation')),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='centers.centers')),
            ],
            options={
                'abstract': False,
            },
            bases=('common.commonlocation', models.Model),
        ),
    ]
